import React, { useState, useRef, useCallback } from 'react';
import {
  Upload,
  ScanLine,
  FileDown,
  X,
  ImagePlus,
  AlertTriangle,
  CheckCircle,
  Loader2,
  Eye,
  ShieldCheck
} from 'lucide-react';

const API_BASE_URL = 'https://hpcl-hackathon-1.onrender.com/api';

// ─── PDF Export ───────────────────────────────────────────────────────────────
function exportReportAsPDF(htmlContent, imageSrc) {
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-IN', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });
  const timeStr = today.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
  const refNo = `HPCL-SIA-${Date.now().toString(36).toUpperCase()}`;

  const imgTag = imageSrc
    ? `<img src="${imageSrc}" style="max-width:320px; max-height:220px; border-radius:8px; border:1px solid #e5e7eb; object-fit:cover;" alt="Inspected Outlet" />`
    : '';

  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>HPCL Smart Inspection Report — ${refNo}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #111827; padding: 24px 32px; }
    @media print {
      body { padding: 0; }
      @page { margin: 1.5cm; size: A4 portrait; }
    }
    .print-header {
      display: flex; justify-content: space-between; align-items: flex-start;
      border-bottom: 2px solid #1e3a8a; padding-bottom: 14px; margin-bottom: 20px;
    }
    .print-meta { font-size: 11px; color: #6b7280; text-align: right; line-height: 1.6; }
    .print-img-row { display: flex; gap: 20px; margin-bottom: 20px; align-items: flex-start; }
    .print-img-label { font-size: 11px; color: #6b7280; margin-top: 6px; }
    .disclaimer {
      margin-top: 24px; padding: 12px 16px; border: 1px solid #fbbf24;
      background: #fffbeb; border-radius: 8px; font-size: 11px; color: #92400e;
    }
  </style>
</head>
<body>
  <div class="print-header">
    <div>
      <div style="font-size:20px;font-weight:800;color:#1e3a8a;">HPCL Smart Inspection Report</div>
      <div style="font-size:12px;color:#6b7280;margin-top:2px;">AI Visual Analysis — Optimized Route Planner</div>
    </div>
    <div class="print-meta">
      <div><strong>Ref No:</strong> ${refNo}</div>
      <div><strong>Date:</strong> ${dateStr}</div>
      <div><strong>Time:</strong> ${timeStr}</div>
      <div><strong>Analysis Engine:</strong> Gemini 2.5 Flash Vision</div>
    </div>
  </div>

  ${imgTag ? `<div class="print-img-row">
    ${imgTag}
    <div class="print-img-label">Photograph submitted for inspection analysis</div>
  </div>` : ''}

  ${htmlContent}

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This report was generated by AI-based visual analysis of a photograph.
    All findings are indicative and must be verified on-site by a qualified HPCL field inspector
    before any compliance or corrective action is initiated.
  </div>

  <script>window.onload = function() { window.print(); };</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(fullHtml);
    win.document.close();
  }
}

const fileToBase64 = (file) => new Promise((resolve, reject) => {
  const reader = new FileReader();
  reader.readAsDataURL(file);
  reader.onload = () => {
    const base64String = reader.result.split(',')[1];
    resolve(base64String);
  };
  reader.onerror = error => reject(error);
});

const inspectionSystemPrompt = `You are an expert HPCL petroleum outlet infrastructure inspector with 20 years of field experience.

You will receive a photograph of a petroleum outlet (petrol station / fuel dispensing facility) and you must produce a COMPLETE, DETAILED inspection report.

CRITICAL FORMATTING RULE: Your ENTIRE response must be valid HTML only. Do NOT use markdown. Do NOT use asterisks. Do NOT use backticks. Do NOT use code fences. Output raw HTML starting with <div and ending with </div>.

Analyse every visible element in the image for:
- Pipeline infrastructure (pipes, joints, flanges, valves, visible corrosion or leaks)
- Dispensing units (dispensers, nozzles, hose condition, display panels)
- Storage and tank area (tank vents, fill covers, bunds, spill containment)
- Electrical and safety systems (earthing, fire extinguishers, signage, emergency stops)
- Housekeeping and civil works (cleanliness, drainage, forecourt, canopy)
- Statutory compliance (licence boards, safety signs, markings)

Output this EXACT HTML structure with real findings filled in (replace all [PLACEHOLDERS]):

<div style="font-family: Segoe UI, Arial, sans-serif; color: #111827;">

  <div style="background: linear-gradient(135deg, #1e3a8a, #2563eb); color: white; padding: 24px 28px; border-radius: 10px 10px 0 0; margin-bottom: 0;">
    <div style="font-size: 20px; font-weight: 800; margin: 0;">HPCL Petroleum Outlet — Visual Inspection Report</div>
    <div style="font-size: 12px; opacity: 0.85; margin-top: 6px;">AI-Powered Infrastructure Analysis | Optimized Route Planner</div>
  </div>

  <div style="background: [USE #16a34a for SATISFACTORY, #d97706 for NEEDS ATTENTION, #dc2626 for CRITICAL]; padding: 14px 28px; display: flex; align-items: center; gap: 16px; margin-bottom: 20px;">
    <div style="font-size: 28px;">[USE checkmark or warning or cross symbol here]</div>
    <div>
      <div style="font-weight: 700; font-size: 15px; color: white;">Overall Status: [SATISFACTORY / NEEDS ATTENTION / CRITICAL]</div>
      <div style="font-size: 12px; color: rgba(255,255,255,0.9); margin-top: 3px;">[Write a single sentence summary of what you found overall]</div>
    </div>
  </div>

  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 20px;">

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Pipeline Infrastructure</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>[Finding 1 about pipes/valves visible in image]</li>
        <li>[Finding 2]</li>
        <li>[Finding 3 or 'Not visible in this image']</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: [#dcfce7 for OK, #fef9c3 for MINOR, #fee2e2 for MAJOR]; color: [#15803d or #a16207 or #b91c1c]; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">[OK / MINOR ISSUE / MAJOR ISSUE]</span>
      </div>
    </div>

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Dispensing Units</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>[Finding about dispensers visible]</li>
        <li>[Finding 2]</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: #dcfce7; color: #15803d; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">OK</span>
      </div>
    </div>

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Safety Systems</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>[Finding about fire extinguisher / earthing / signage]</li>
        <li>[Finding 2]</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: #dcfce7; color: #15803d; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">OK</span>
      </div>
    </div>

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Housekeeping & Civil Works</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>[Finding about cleanliness, drainage, forecourt]</li>
        <li>[Finding 2]</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: #dcfce7; color: #15803d; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">OK</span>
      </div>
    </div>

  </div>

  <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px; margin-bottom: 20px;">
    <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.5px;">Detailed Observations Table</div>
    <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
      <thead>
        <tr style="background: #1e40af; color: white;">
          <th style="padding: 9px 12px; text-align: left; border-radius: 0;">Category</th>
          <th style="padding: 9px 12px; text-align: left;">Finding</th>
          <th style="padding: 9px 12px; text-align: center;">Severity</th>
          <th style="padding: 9px 12px; text-align: left;">Recommended Action</th>
        </tr>
      </thead>
      <tbody>
        <tr style="background: white; border-bottom: 1px solid #f3f4f6;">
          <td style="padding: 8px 12px; color: #374151;">[Category e.g. Pipeline]</td>
          <td style="padding: 8px 12px; color: #374151;">[Specific finding from image]</td>
          <td style="padding: 8px 12px; text-align: center;"><span style="background: #dcfce7; color: #15803d; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 700;">Minor</span></td>
          <td style="padding: 8px 12px; color: #374151;">[Action to take]</td>
        </tr>
        <tr style="background: #f9fafb; border-bottom: 1px solid #f3f4f6;">
          <td style="padding: 8px 12px; color: #374151;">[Category]</td>
          <td style="padding: 8px 12px; color: #374151;">[Finding]</td>
          <td style="padding: 8px 12px; text-align: center;"><span style="background: #fee2e2; color: #b91c1c; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 700;">Major</span></td>
          <td style="padding: 8px 12px; color: #374151;">[Action]</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div style="background: #fff7ed; border: 1px solid #fed7aa; border-radius: 10px; padding: 16px; margin-bottom: 16px;">
    <div style="font-weight: 700; font-size: 13px; color: #c2410c; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Priority Action Items</div>
    <ol style="margin: 0; padding-left: 20px; font-size: 13px; color: #374151; line-height: 1.8;">
      <li>[Immediate action 1 required based on findings]</li>
      <li>[Action 2]</li>
      <li>[Action 3 or 'No immediate actions required if satisfactory']</li>
    </ol>
  </div>

  <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 12px 16px; font-size: 11px; color: #1e40af;">
    This report was generated by AI visual analysis. Field verification by a qualified HPCL inspector is mandatory before any compliance action.
  </div>

</div>

Fill in ALL placeholder text [in brackets] with your real observations from the image. If a section is not visible in the image, state "Not visible in this photograph." Be specific and detailed about what you actually see.`;

const fallbackHtmlReport = `<div style="font-family: Segoe UI, Arial, sans-serif; color: #111827;">

  <div style="background: linear-gradient(135deg, #1e3a8a, #2563eb); color: white; padding: 24px 28px; border-radius: 10px 10px 0 0; margin-bottom: 0;">
    <div style="font-size: 20px; font-weight: 800; margin: 0;">HPCL Petroleum Outlet — Visual Inspection Report (Fallback Demo)</div>
    <div style="font-size: 12px; opacity: 0.85; margin-top: 6px;">AI-Powered Infrastructure Analysis | Offline Demo Mode</div>
  </div>

  <div style="background: #d97706; padding: 14px 28px; display: flex; align-items: center; gap: 16px; margin-bottom: 20px;">
    <div style="font-size: 28px;">⚠</div>
    <div>
      <div style="font-weight: 700; font-size: 15px; color: white;">Overall Status: NEEDS ATTENTION (Fallback Demo)</div>
      <div style="font-size: 12px; color: rgba(255,255,255,0.9); margin-top: 3px;">The API key is missing or invalid. Displaying a predefined inspection report for demonstration purposes. Minor issues detected on forecourt area.</div>
    </div>
  </div>

  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 20px;">

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Pipeline Infrastructure</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>All visible pipes show standard green anti-corrosion coating.</li>
        <li>Flanges and joints are securely bolted with no visible signs of product weeping or leakage.</li>
        <li>Pressure gauges read within operational ranges.</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: #dcfce7; color: #15803d; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">OK</span>
      </div>
    </div>

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Dispensing Units</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>Dispenser housings are clean and intact with clear digital displays.</li>
        <li>Delivery hose shows minor scuffing near the nozzle junction (requires monitoring).</li>
        <li>Emergency shear valves are correctly positioned.</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: #fef9c3; color: #a16207; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">MINOR ISSUE</span>
      </div>
    </div>

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Safety Systems</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>Fire extinguishers are mounted in designated areas with inspection tags valid.</li>
        <li>Earthing connections are verified and paint-coded.</li>
        <li>Mandatory safety signage is clearly visible on the canopy columns.</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: #dcfce7; color: #15803d; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">OK</span>
      </div>
    </div>

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px;">
      <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Housekeeping & Civil Works</div>
      <ul style="margin: 0; padding-left: 18px; font-size: 13px; color: #374151; line-height: 1.7;">
        <li>Forecourt is clear of debris; however, minor oil staining is visible near dispensing bay 2.</li>
        <li>Canopy structure is in good condition; drainage channels are clear of obstruction.</li>
      </ul>
      <div style="margin-top: 10px;">
        <span style="background: #fef9c3; color: #a16207; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;">MINOR ISSUE</span>
      </div>
    </div>

  </div>

  <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px; margin-bottom: 20px;">
    <div style="font-weight: 700; font-size: 13px; color: #1e40af; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.5px;">Detailed Observations Table</div>
    <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
      <thead>
        <tr style="background: #1e40af; color: white;">
          <th style="padding: 9px 12px; text-align: left; border-radius: 0;">Category</th>
          <th style="padding: 9px 12px; text-align: left;">Finding</th>
          <th style="padding: 9px 12px; text-align: center;">Severity</th>
          <th style="padding: 9px 12px; text-align: left;">Recommended Action</th>
        </tr>
      </thead>
      <tbody>
        <tr style="background: white; border-bottom: 1px solid #f3f4f6;">
          <td style="padding: 8px 12px; color: #374151;">Dispensing Units</td>
          <td style="padding: 8px 12px; color: #374151;">Minor wear/scuffing on product delivery hoses.</td>
          <td style="padding: 8px 12px; text-align: center;"><span style="background: #fef9c3; color: #a16207; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 700;">Minor</span></td>
          <td style="padding: 8px 12px; color: #374151;">Schedule standard replacement during next regular maintenance cycle.</td>
        </tr>
        <tr style="background: #f9fafb; border-bottom: 1px solid #f3f4f6;">
          <td style="padding: 8px 12px; color: #374151;">Housekeeping</td>
          <td style="padding: 8px 12px; color: #374151;">Oil stains present on concrete forecourt near Dispenser 2.</td>
          <td style="padding: 8px 12px; text-align: center;"><span style="background: #fef9c3; color: #a16207; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 700;">Minor</span></td>
          <td style="padding: 8px 12px; color: #374151;">Apply dry absorbent powder and wash forecourt.</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div style="background: #fff7ed; border: 1px solid #fed7aa; border-radius: 10px; padding: 16px; margin-bottom: 16px;">
    <div style="font-weight: 700; font-size: 13px; color: #c2410c; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Priority Action Items</div>
    <ol style="margin: 0; padding-left: 20px; font-size: 13px; color: #374151; line-height: 1.8;">
      <li>Clean forecourt oil stains to prevent slips/fire hazards.</li>
      <li>Replace wear-damaged delivery hoses on Dispenser 2.</li>
    </ol>
  </div>

  <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 12px 16px; font-size: 11px; color: #1e40af;">
    This report was generated in offline mode due to an API Key configuration error. Field verification by a qualified HPCL inspector is mandatory.
  </div>

</div>`;

// ─── Main Component ───────────────────────────────────────────────────────────
export default function InspectionAnalyser() {
  const [dragOver, setDragOver] = useState(false);
  const [imageFile, setImageFile] = useState(null);
  const [imageSrc, setImageSrc] = useState(null);
  const [analysing, setAnalysing] = useState(false);
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null);
  const fileInputRef = useRef(null);
  const reportRef = useRef(null);

  const handleFile = useCallback((file) => {
    if (!file) return;
    const allowed = ['image/jpeg', 'image/png', 'image/webp'];
    if (!allowed.includes(file.type)) {
      setError('Unsupported format. Please upload a JPEG, PNG, or WEBP image.');
      return;
    }
    if (file.size > 10 * 1024 * 1024) {
      setError('File too large. Maximum size is 10 MB.');
      return;
    }
    setError(null);
    setReport(null);
    setImageFile(file);
    const reader = new FileReader();
    reader.onload = (e) => setImageSrc(e.target.result);
    reader.readAsDataURL(file);
  }, []);

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files[0];
    handleFile(file);
  }, [handleFile]);

  const handleDragOver = (e) => { e.preventDefault(); setDragOver(true); };
  const handleDragLeave = () => setDragOver(false);

  const handleAnalyse = async () => {
    if (!imageFile) return;
    setAnalysing(true);
    setError(null);
    setReport(null);

    const apiKey = import.meta.env.VITE_GEMINI_API_KEY || import.meta.env.VITE_GOOGLE_API_KEY;
    const isPlaceholder = !apiKey || ["YOUR_API_KEY", "PLACEHOLDER", "INSERT_KEY"].some(p => apiKey.toUpperCase().includes(p));

    if (isPlaceholder) {
      setTimeout(() => {
        setReport(fallbackHtmlReport);
        setAnalysing(false);
        setTimeout(() => reportRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
      }, 1000);
      return;
    }

    try {
      const base64Data = await fileToBase64(imageFile);
      const mimeType = imageFile.type || 'image/jpeg';
      
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
      
      const payload = {
        contents: [
          {
            role: "user",
            parts: [
              {
                inline_data: {
                  mime_type: mimeType,
                  data: base64Data
                }
              },
              {
                text: "Analyse this petroleum outlet image thoroughly. Produce the complete HTML inspection report exactly as instructed. Start your response with <div and end with </div>. Do not write anything before <div or after </div>."
              }
            ]
          }
        ],
        systemInstruction: {
          parts: [{ text: inspectionSystemPrompt }]
        },
        generationConfig: {
          temperature: 0.1,
          maxOutputTokens: 6000
        }
      };

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (response.status === 200) {
        const result = await response.json();
        let raw = result.candidates[0].content.parts[0].text;
        
        let html = raw.trim();
        html = html.replace(/^```[a-zA-Z]*\s*/gm, '');
        html = html.replace(/```\s*$/gm, '');
        html = html.trim();
        
        if (!html.startsWith("<")) {
          html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
          html = `<div style="font-family: Segoe UI, Arial, sans-serif; color: #111827; padding: 20px;">
  <div style="background: linear-gradient(135deg,#1e3a8a,#2563eb);color:white;padding:20px;border-radius:8px;margin-bottom:16px;">
    <div style="font-size:18px;font-weight:800;">HPCL Petroleum Outlet — Visual Inspection Report</div>
  </div>
  <div style="white-space: pre-wrap; font-size: 13px; line-height: 1.7; color: #374151;">${html}</div>
</div>`;
        }
        
        setReport(html);
      } else {
        setReport(fallbackHtmlReport);
      }
      setTimeout(() => reportRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    } catch (err) {
      console.error(err);
      setReport(fallbackHtmlReport);
      setTimeout(() => reportRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    } finally {
      setAnalysing(false);
    }
  };

  const handleClear = () => {
    setImageFile(null);
    setImageSrc(null);
    setReport(null);
    setError(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    <div className="animate-fade-in" style={{ padding: '1.5rem', height: '100%', overflowY: 'auto' }}>

      {/* Page Header */}
      <div className="glass-panel" style={{ padding: '1.5rem 2rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div style={{
            width: '48px', height: '48px',
            background: 'linear-gradient(135deg, #7c3aed, #4f46e5)',
            borderRadius: '12px',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 4px 16px rgba(124,58,237,0.4)'
          }}>
            <ScanLine size={24} color="#fff" />
          </div>
          <div>
            <h2 style={{ fontSize: '1.25rem', fontWeight: 800 }}>Smart Inspection Analyser</h2>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginTop: '2px' }}>
              Upload a petroleum outlet photograph — Gemini AI analyses pipelines, dispensers, safety systems & more
            </p>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
          <ShieldCheck size={14} style={{ color: '#7c3aed' }} />
          Powered by Gemini 2.5 Flash Vision
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.6fr', gap: '1.5rem', alignItems: 'start' }}>

        {/* ── Left: Upload Panel ── */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

          {/* Drop Zone */}
          <div
            className="glass-panel"
            onClick={() => !imageSrc && fileInputRef.current?.click()}
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            style={{
              padding: '0',
              border: dragOver
                ? '2px dashed #7c3aed'
                : imageSrc ? '2px solid rgba(124,58,237,0.3)' : '2px dashed rgba(255,255,255,0.1)',
              borderRadius: '16px',
              cursor: imageSrc ? 'default' : 'pointer',
              transition: 'border-color 0.2s, background 0.2s',
              background: dragOver ? 'rgba(124,58,237,0.08)' : 'var(--bg-card)',
              overflow: 'hidden',
              position: 'relative'
            }}
          >
            {imageSrc ? (
              <>
                <img
                  src={imageSrc}
                  alt="Uploaded outlet"
                  style={{ width: '100%', maxHeight: '280px', objectFit: 'cover', display: 'block' }}
                />
                {/* Clear button */}
                <button
                  onClick={(e) => { e.stopPropagation(); handleClear(); }}
                  style={{
                    position: 'absolute', top: '10px', right: '10px',
                    background: 'rgba(0,0,0,0.65)', border: 'none', color: '#fff',
                    width: '28px', height: '28px', borderRadius: '50%',
                    cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center'
                  }}
                >
                  <X size={14} />
                </button>
                {/* File info */}
                <div style={{ padding: '10px 14px', borderTop: '1px solid var(--border-color)', fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                  <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{imageFile?.name}</span>
                  <span style={{ marginLeft: '8px' }}>({(imageFile?.size / 1024).toFixed(0)} KB)</span>
                </div>
              </>
            ) : (
              <div style={{ padding: '3rem 2rem', textAlign: 'center' }}>
                <div style={{
                  width: '56px', height: '56px', borderRadius: '14px',
                  background: 'rgba(124,58,237,0.12)', border: '1px solid rgba(124,58,237,0.2)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  margin: '0 auto 1rem'
                }}>
                  <ImagePlus size={26} style={{ color: '#7c3aed' }} />
                </div>
                <p style={{ fontWeight: 700, fontSize: '0.95rem', marginBottom: '0.4rem' }}>
                  Drop outlet image here
                </p>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '1.2rem' }}>
                  or click to browse — JPEG, PNG, WEBP up to 10 MB
                </p>
                <div style={{
                  display: 'inline-flex', alignItems: 'center', gap: '0.4rem',
                  background: 'rgba(124,58,237,0.15)', border: '1px solid rgba(124,58,237,0.3)',
                  color: '#a78bfa', borderRadius: '8px', padding: '6px 16px', fontSize: '0.82rem', fontWeight: 600
                }}>
                  <Upload size={14} /> Choose Image
                </div>
              </div>
            )}
          </div>

          <input
            ref={fileInputRef}
            type="file"
            accept="image/jpeg,image/png,image/webp"
            style={{ display: 'none' }}
            onChange={(e) => handleFile(e.target.files[0])}
          />

          {/* Error */}
          {error && (
            <div style={{
              display: 'flex', alignItems: 'flex-start', gap: '0.5rem',
              background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.25)',
              borderRadius: '10px', padding: '10px 14px', fontSize: '0.82rem', color: '#f87171'
            }}>
              <AlertTriangle size={15} style={{ flexShrink: 0, marginTop: '1px' }} />
              {error}
            </div>
          )}

          {/* Analyse Button */}
          <button
            onClick={handleAnalyse}
            disabled={!imageFile || analysing}
            style={{
              width: '100%',
              padding: '12px',
              background: imageFile && !analysing
                ? 'linear-gradient(135deg, #7c3aed, #4f46e5)'
                : 'rgba(255,255,255,0.05)',
              color: imageFile && !analysing ? '#fff' : 'var(--text-muted)',
              border: 'none',
              borderRadius: '10px',
              fontSize: '0.92rem',
              fontWeight: 700,
              cursor: imageFile && !analysing ? 'pointer' : 'not-allowed',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '0.5rem',
              transition: 'all 0.2s',
              boxShadow: imageFile && !analysing ? '0 4px 16px rgba(124,58,237,0.35)' : 'none'
            }}
          >
            {analysing ? (
              <>
                <Loader2 size={17} style={{ animation: 'spin 1s linear infinite' }} />
                Analysing Image...
              </>
            ) : (
              <>
                <Eye size={17} />
                Run AI Inspection Analysis
              </>
            )}
          </button>

          {/* What it checks */}
          <div className="glass-panel" style={{ padding: '1rem 1.25rem' }}>
            <p style={{ fontSize: '0.78rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '0.6rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              What Gemini Analyses
            </p>
            {[
              'Pipeline joints, valves & corrosion',
              'Dispensing units & nozzle condition',
              'Storage tanks & spill containment',
              'Electrical & fire safety systems',
              'Housekeeping & civil infrastructure',
              'Statutory signage & compliance markings'
            ].map((item, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem', color: 'var(--text-primary)', marginBottom: '0.35rem' }}>
                <CheckCircle size={12} style={{ color: '#10b981', flexShrink: 0 }} />
                {item}
              </div>
            ))}
          </div>
        </div>

        {/* ── Right: Report Panel ── */}
        <div ref={reportRef}>
          {!report && !analysing && (
            <div className="glass-panel" style={{
              padding: '4rem 2rem', textAlign: 'center',
              border: '2px dashed rgba(255,255,255,0.06)'
            }}>
              <ScanLine size={48} style={{ color: 'rgba(124,58,237,0.3)', marginBottom: '1rem' }} />
              <p style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
                No report generated yet
              </p>
              <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                Upload a petroleum outlet photograph and click "Run AI Inspection Analysis"
              </p>
            </div>
          )}

          {analysing && (
            <div className="glass-panel" style={{ padding: '4rem 2rem', textAlign: 'center' }}>
              <div style={{
                width: '64px', height: '64px', borderRadius: '50%',
                background: 'linear-gradient(135deg, rgba(124,58,237,0.2), rgba(79,70,229,0.2))',
                border: '2px solid rgba(124,58,237,0.3)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                margin: '0 auto 1.25rem',
                animation: 'pulse 1.5s ease-in-out infinite'
              }}>
                <ScanLine size={28} style={{ color: '#7c3aed' }} />
              </div>
              <p style={{ fontWeight: 700, fontSize: '1rem', marginBottom: '0.5rem' }}>Gemini is analysing your image...</p>
              <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                Examining pipelines, dispensers, safety systems and compliance markers
              </p>
            </div>
          )}

          {report && (
            <div className="glass-panel" style={{ padding: '0', overflow: 'hidden' }}>
              {/* Report Toolbar */}
              <div style={{
                padding: '0.9rem 1.25rem',
                borderBottom: '1px solid var(--border-color)',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <CheckCircle size={16} style={{ color: '#10b981' }} />
                  <span style={{ fontWeight: 700, fontSize: '0.9rem' }}>Inspection Report Generated</span>
                </div>
                <button
                  onClick={() => exportReportAsPDF(report, imageSrc)}
                  style={{
                    display: 'flex', alignItems: 'center', gap: '0.4rem',
                    background: 'linear-gradient(135deg, #1e40af, #3b82f6)',
                    color: '#fff', border: 'none', borderRadius: '8px',
                    padding: '7px 16px', fontSize: '0.8rem', fontWeight: 700,
                    cursor: 'pointer', boxShadow: '0 2px 8px rgba(59,130,246,0.35)',
                    transition: 'opacity 0.2s'
                  }}
                  onMouseEnter={e => e.currentTarget.style.opacity = '0.85'}
                  onMouseLeave={e => e.currentTarget.style.opacity = '1'}
                >
                  <FileDown size={14} />
                  Export PDF
                </button>
              </div>

              {/* Rendered HTML Report */}
              <div
                style={{
                  padding: '1.5rem',
                  maxHeight: '68vh',
                  overflowY: 'auto',
                  background: '#ffffff',
                  color: '#111827'
                }}
                dangerouslySetInnerHTML={{ __html: report }}
              />
            </div>
          )}
        </div>
      </div>

      <style>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.6; } }
      `}</style>
    </div>
  );
}
