import React, { useState, useRef, useCallback } from 'react';
import {
  Upload,
  ScanLine,
  FileDown,
  X,
  ImagePlus,
  AlertTriangle,
  CheckCircle,
  Loader2,
  Eye,
  ShieldCheck
} from 'lucide-react';

const API_BASE_URL = 'https://hpcl-hackathon-1.onrender.com/api';

// ─── PDF Export ───────────────────────────────────────────────────────────────
function exportReportAsPDF(htmlContent, imageSrc) {
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-IN', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });
  const timeStr = today.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
  const refNo = `HPCL-SIA-${Date.now().toString(36).toUpperCase()}`;

  const imgTag = imageSrc
    ? `<img src="${imageSrc}" style="max-width:320px; max-height:220px; border-radius:8px; border:1px solid #e5e7eb; object-fit:cover;" alt="Inspected Outlet" />`
    : '';

  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>HPCL Smart Inspection Report — ${refNo}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #111827; padding: 24px 32px; }
    @media print {
      body { padding: 0; }
      @page { margin: 1.5cm; size: A4 portrait; }
    }
    .print-header {
      display: flex; justify-content: space-between; align-items: flex-start;
      border-bottom: 2px solid #1e3a8a; padding-bottom: 14px; margin-bottom: 20px;
    }
    .print-meta { font-size: 11px; color: #6b7280; text-align: right; line-height: 1.6; }
    .print-img-row { display: flex; gap: 20px; margin-bottom: 20px; align-items: flex-start; }
    .print-img-label { font-size: 11px; color: #6b7280; margin-top: 6px; }
    .disclaimer {
      margin-top: 24px; padding: 12px 16px; border: 1px solid #fbbf24;
      background: #fffbeb; border-radius: 8px; font-size: 11px; color: #92400e;
    }
  </style>
</head>
<body>
  <div class="print-header">
    <div>
      <div style="font-size:20px;font-weight:800;color:#1e3a8a;">HPCL Smart Inspection Report</div>
      <div style="font-size:12px;color:#6b7280;margin-top:2px;">AI Visual Analysis — Optimized Route Planner</div>
    </div>
    <div class="print-meta">
      <div><strong>Ref No:</strong> ${refNo}</div>
      <div><strong>Date:</strong> ${dateStr}</div>
      <div><strong>Time:</strong> ${timeStr}</div>
      <div><strong>Analysis Engine:</strong> Gemini 2.5 Flash Vision</div>
    </div>
  </div>

  ${imgTag ? `<div class="print-img-row">
    ${imgTag}
    <div class="print-img-label">Photograph submitted for inspection analysis</div>
  </div>` : ''}

  ${htmlContent}

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This report was generated by AI-based visual analysis of a photograph.
    All findings are indicative and must be verified on-site by a qualified HPCL field inspector
    before any compliance or corrective action is initiated.
  </div>

  <script>window.onload = function() { window.print(); };</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(fullHtml);
    win.document.close();
  }
}

// ─── Main Component ───────────────────────────────────────────────────────────
export default function InspectionAnalyser() {
  const [dragOver, setDragOver] = useState(false);
  const [imageFile, setImageFile] = useState(null);
  const [imageSrc, setImageSrc] = useState(null);
  const [analysing, setAnalysing] = useState(false);
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null);
  const fileInputRef = useRef(null);
  const reportRef = useRef(null);

  const handleFile = useCallback((file) => {
    if (!file) return;
    const allowed = ['image/jpeg', 'image/png', 'image/webp'];
    if (!allowed.includes(file.type)) {
      setError('Unsupported format. Please upload a JPEG, PNG, or WEBP image.');
      return;
    }
    if (file.size > 10 * 1024 * 1024) {
      setError('File too large. Maximum size is 10 MB.');
      return;
    }
    setError(null);
    setReport(null);
    setImageFile(file);
    const reader = new FileReader();
    reader.onload = (e) => setImageSrc(e.target.result);
    reader.readAsDataURL(file);
  }, []);

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files[0];
    handleFile(file);
  }, [handleFile]);

  const handleDragOver = (e) => { e.preventDefault(); setDragOver(true); };
  const handleDragLeave = () => setDragOver(false);

  const handleAnalyse = async () => {
    if (!imageFile) return;
    setAnalysing(true);
    setError(null);
    setReport(null);

    const formData = new FormData();
    formData.append('file', imageFile);

    try {
      const res = await fetch(`${API_BASE_URL}/analyse-image`, {
        method: 'POST',
        body: formData
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || 'Analysis failed');
      setReport(data.report);
      setTimeout(() => reportRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    } catch (err) {
      setError(`Analysis failed: ${err.message}`);
    } finally {
      setAnalysing(false);
    }
  };

  const handleClear = () => {
    setImageFile(null);
    setImageSrc(null);
    setReport(null);
    setError(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    <div className="animate-fade-in" style={{ padding: '1.5rem', height: '100%', overflowY: 'auto' }}>

      {/* Page Header */}
      <div className="glass-panel" style={{ padding: '1.5rem 2rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div style={{
            width: '48px', height: '48px',
            background: 'linear-gradient(135deg, #7c3aed, #4f46e5)',
            borderRadius: '12px',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 4px 16px rgba(124,58,237,0.4)'
          }}>
            <ScanLine size={24} color="#fff" />
          </div>
          <div>
            <h2 style={{ fontSize: '1.25rem', fontWeight: 800 }}>Smart Inspection Analyser</h2>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginTop: '2px' }}>
              Upload a petroleum outlet photograph — Gemini AI analyses pipelines, dispensers, safety systems & more
            </p>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
          <ShieldCheck size={14} style={{ color: '#7c3aed' }} />
          Powered by Gemini 2.5 Flash Vision
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.6fr', gap: '1.5rem', alignItems: 'start' }}>

        {/* ── Left: Upload Panel ── */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

          {/* Drop Zone */}
          <div
            className="glass-panel"
            onClick={() => !imageSrc && fileInputRef.current?.click()}
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            style={{
              padding: '0',
              border: dragOver
                ? '2px dashed #7c3aed'
                : imageSrc ? '2px solid rgba(124,58,237,0.3)' : '2px dashed rgba(255,255,255,0.1)',
              borderRadius: '16px',
              cursor: imageSrc ? 'default' : 'pointer',
              transition: 'border-color 0.2s, background 0.2s',
              background: dragOver ? 'rgba(124,58,237,0.08)' : 'var(--bg-card)',
              overflow: 'hidden',
              position: 'relative'
            }}
          >
            {imageSrc ? (
              <>
                <img
                  src={imageSrc}
                  alt="Uploaded outlet"
                  style={{ width: '100%', maxHeight: '280px', objectFit: 'cover', display: 'block' }}
                />
                {/* Clear button */}
                <button
                  onClick={(e) => { e.stopPropagation(); handleClear(); }}
                  style={{
                    position: 'absolute', top: '10px', right: '10px',
                    background: 'rgba(0,0,0,0.65)', border: 'none', color: '#fff',
                    width: '28px', height: '28px', borderRadius: '50%',
                    cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center'
                  }}
                >
                  <X size={14} />
                </button>
                {/* File info */}
                <div style={{ padding: '10px 14px', borderTop: '1px solid var(--border-color)', fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                  <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{imageFile?.name}</span>
                  <span style={{ marginLeft: '8px' }}>({(imageFile?.size / 1024).toFixed(0)} KB)</span>
                </div>
              </>
            ) : (
              <div style={{ padding: '3rem 2rem', textAlign: 'center' }}>
                <div style={{
                  width: '56px', height: '56px', borderRadius: '14px',
                  background: 'rgba(124,58,237,0.12)', border: '1px solid rgba(124,58,237,0.2)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  margin: '0 auto 1rem'
                }}>
                  <ImagePlus size={26} style={{ color: '#7c3aed' }} />
                </div>
                <p style={{ fontWeight: 700, fontSize: '0.95rem', marginBottom: '0.4rem' }}>
                  Drop outlet image here
                </p>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '1.2rem' }}>
                  or click to browse — JPEG, PNG, WEBP up to 10 MB
                </p>
                <div style={{
                  display: 'inline-flex', alignItems: 'center', gap: '0.4rem',
                  background: 'rgba(124,58,237,0.15)', border: '1px solid rgba(124,58,237,0.3)',
                  color: '#a78bfa', borderRadius: '8px', padding: '6px 16px', fontSize: '0.82rem', fontWeight: 600
                }}>
                  <Upload size={14} /> Choose Image
                </div>
              </div>
            )}
          </div>

          <input
            ref={fileInputRef}
            type="file"
            accept="image/jpeg,image/png,image/webp"
            style={{ display: 'none' }}
            onChange={(e) => handleFile(e.target.files[0])}
          />

          {/* Error */}
          {error && (
            <div style={{
              display: 'flex', alignItems: 'flex-start', gap: '0.5rem',
              background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.25)',
              borderRadius: '10px', padding: '10px 14px', fontSize: '0.82rem', color: '#f87171'
            }}>
              <AlertTriangle size={15} style={{ flexShrink: 0, marginTop: '1px' }} />
              {error}
            </div>
          )}

          {/* Analyse Button */}
          <button
            onClick={handleAnalyse}
            disabled={!imageFile || analysing}
            style={{
              width: '100%',
              padding: '12px',
              background: imageFile && !analysing
                ? 'linear-gradient(135deg, #7c3aed, #4f46e5)'
                : 'rgba(255,255,255,0.05)',
              color: imageFile && !analysing ? '#fff' : 'var(--text-muted)',
              border: 'none',
              borderRadius: '10px',
              fontSize: '0.92rem',
              fontWeight: 700,
              cursor: imageFile && !analysing ? 'pointer' : 'not-allowed',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '0.5rem',
              transition: 'all 0.2s',
              boxShadow: imageFile && !analysing ? '0 4px 16px rgba(124,58,237,0.35)' : 'none'
            }}
          >
            {analysing ? (
              <>
                <Loader2 size={17} style={{ animation: 'spin 1s linear infinite' }} />
                Analysing Image...
              </>
            ) : (
              <>
                <Eye size={17} />
                Run AI Inspection Analysis
              </>
            )}
          </button>

          {/* What it checks */}
          <div className="glass-panel" style={{ padding: '1rem 1.25rem' }}>
            <p style={{ fontSize: '0.78rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '0.6rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              What Gemini Analyses
            </p>
            {[
              'Pipeline joints, valves & corrosion',
              'Dispensing units & nozzle condition',
              'Storage tanks & spill containment',
              'Electrical & fire safety systems',
              'Housekeeping & civil infrastructure',
              'Statutory signage & compliance markings'
            ].map((item, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem', color: 'var(--text-primary)', marginBottom: '0.35rem' }}>
                <CheckCircle size={12} style={{ color: '#10b981', flexShrink: 0 }} />
                {item}
              </div>
            ))}
          </div>
        </div>

        {/* ── Right: Report Panel ── */}
        <div ref={reportRef}>
          {!report && !analysing && (
            <div className="glass-panel" style={{
              padding: '4rem 2rem', textAlign: 'center',
              border: '2px dashed rgba(255,255,255,0.06)'
            }}>
              <ScanLine size={48} style={{ color: 'rgba(124,58,237,0.3)', marginBottom: '1rem' }} />
              <p style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
                No report generated yet
              </p>
              <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                Upload a petroleum outlet photograph and click "Run AI Inspection Analysis"
              </p>
            </div>
          )}

          {analysing && (
            <div className="glass-panel" style={{ padding: '4rem 2rem', textAlign: 'center' }}>
              <div style={{
                width: '64px', height: '64px', borderRadius: '50%',
                background: 'linear-gradient(135deg, rgba(124,58,237,0.2), rgba(79,70,229,0.2))',
                border: '2px solid rgba(124,58,237,0.3)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                margin: '0 auto 1.25rem',
                animation: 'pulse 1.5s ease-in-out infinite'
              }}>
                <ScanLine size={28} style={{ color: '#7c3aed' }} />
              </div>
              <p style={{ fontWeight: 700, fontSize: '1rem', marginBottom: '0.5rem' }}>Gemini is analysing your image...</p>
              <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                Examining pipelines, dispensers, safety systems and compliance markers
              </p>
            </div>
          )}

          {report && (
            <div className="glass-panel" style={{ padding: '0', overflow: 'hidden' }}>
              {/* Report Toolbar */}
              <div style={{
                padding: '0.9rem 1.25rem',
                borderBottom: '1px solid var(--border-color)',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <CheckCircle size={16} style={{ color: '#10b981' }} />
                  <span style={{ fontWeight: 700, fontSize: '0.9rem' }}>Inspection Report Generated</span>
                </div>
                <button
                  onClick={() => exportReportAsPDF(report, imageSrc)}
                  style={{
                    display: 'flex', alignItems: 'center', gap: '0.4rem',
                    background: 'linear-gradient(135deg, #1e40af, #3b82f6)',
                    color: '#fff', border: 'none', borderRadius: '8px',
                    padding: '7px 16px', fontSize: '0.8rem', fontWeight: 700,
                    cursor: 'pointer', boxShadow: '0 2px 8px rgba(59,130,246,0.35)',
                    transition: 'opacity 0.2s'
                  }}
                  onMouseEnter={e => e.currentTarget.style.opacity = '0.85'}
                  onMouseLeave={e => e.currentTarget.style.opacity = '1'}
                >
                  <FileDown size={14} />
                  Export PDF
                </button>
              </div>

              {/* Rendered HTML Report */}
              <div
                style={{
                  padding: '1.5rem',
                  maxHeight: '68vh',
                  overflowY: 'auto',
                  background: '#ffffff',
                  color: '#111827'
                }}
                dangerouslySetInnerHTML={{ __html: report }}
              />
            </div>
          )}
        </div>
      </div>

      <style>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.6; } }
      `}</style>
    </div>
  );
}
